name: Heat sensor
on: [ issues, pull_request, issue_comment, pull_request_review, pull_request_review_comment ]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  detect-heat:
    uses: jonathanpeppers/inclusive-heat-sensor/.github/workflows/comments.yml@rolf/dev/ghactions
    with:
      sensitivity: "0.5"
